services:

  mysql:
    image: mysql:8.0
    container_name: gso_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 23-Shai-01186
      MYSQL_DATABASE: manageit
    ports:
      - "5506:3306" # Avoid conflict with local MySQL
    volumes:
      - ./docker-data/mysql_data:/var/lib/mysql
    networks:
      - gso_network

  backend:
    build:
      context: ./docker-gsobackend
      dockerfile: backend.dockerfile
    container_name: gso_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: manageit
      DB_USERNAME: root
      DB_PASSWORD: 23-Shai-01186
    ports:
      - "9000:8000"
    volumes:
      - ./docker-data/backend_pictures:/var/www/html/storage/app/public
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - gso_network

  queue_worker:
    build:
      context: ./docker-gsobackend
      dockerfile: backend.dockerfile
    container_name: gso_queue_worker
    restart: always
    depends_on:
      - mysql
      - backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: manageit
      DB_USERNAME: root
      DB_PASSWORD: 23-Shai-01186
    volumes:
      - ./docker-data/backend_pictures:/var/www/html/storage/app/public
    command: php artisan queue:work --tries=3
    networks:
      - gso_network

  frontend:
    build:
      context: ./docker-gsofrontend
      dockerfile: frontend.dockerfile
    container_name: gso_frontend
    restart: always
    ports:
      - "90:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    networks:
      - gso_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gso_phpmyadmin
    restart: always
    environment:
      PMA_HOST: gso_mysql
      PMA_USER: root
      PMA_PASSWORD: 23-Shai-01186
    ports:
      - "9090:80" # Access phpMyAdmin via localhost:8080
    depends_on:
      - mysql
    networks:
      - gso_network

networks:
  gso_network:


